/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package agendae;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author user
 */
public class GuiAgenda extends javax.swing.JFrame {
    Connection conn=null;
    Statement statement=null;
    /**
     * Creates new form GuiCmmdc
     */
    public GuiAgenda() {
        initComponents();
        /*
        String driver="org.apache.derby.jdbc.ClientDriver";
        String dbName="jdbc:derby://localhost:1527/AgendaEMail";
        */
        String driver="com.mysql.jdbc.Driver";
        String dbName="jdbc:mysql://localhost:3306/AgendaEMail?user=root";

        try{
          Class.forName(driver);
          conn = DriverManager.getConnection(dbName);
          statement=conn.createStatement();
        }
        catch(ClassNotFoundException e){
          System.out.println("Driver inexistent JDBC: "+driver);
        }
        catch(SQLException e){
          System.out.println("Baza de date inexistenta "+dbName);
        }
        catch(Exception e){
          System.out.println("Eroare : "+e.getMessage());
        }  
     }   

        
        
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDB = new javax.swing.JTextArea();
        jTextFieldEntit = new javax.swing.JTextField();
        jComboBoxTip = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonExec.setText("Executa");
        jButtonExec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExecMouseClicked(evt);
            }
        });

        jTextAreaDB.setColumns(20);
        jTextAreaDB.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDB);

        jComboBoxTip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nume", "Adresa e-main", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonExec)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jTextFieldEntit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonExec)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEntit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExecMouseClicked
    // TODO add your handling code here:
      int prel=jComboBoxTip.getSelectedIndex();
      String entit='\''+jTextFieldEntit.getText().trim()+'\'';
      String sql;
      ResultSet rs=null;
      jTextAreaDB.setText("");
      StringBuilder sb=new StringBuilder(100);
      try{
        switch(prel){
          case 0 :
            sql="select * from adrese where nume="+entit;
            rs=statement.executeQuery(sql);
            if(rs!=null){
              while(rs.next()){
                //sb.append(rs.getString("nume")+" : "+rs.getString("email")+"\n"); 
                sb.append(rs.getString("nume"));
                sb.append(" : ");
                sb.append(rs.getString("email"));
                sb.append("\n");
              }
            }
            else{
              sb.append("Fara adresa de e-mail !");
            }           
            break;
          case 1 :
            sql="select * from adrese where email="+entit;
            rs=statement.executeQuery(sql);
            if(rs!=null){
              while(rs.next()){
                //sb.append(rs.getString("nume")+" : "+rs.getString("email")+"\n");
                sb.append(rs.getString("nume"));
                sb.append(" : ");
                sb.append(rs.getString("email"));
                sb.append("\n");
              }
            }
        } 
      }
      catch(SQLException e){    
        System.out.println("Query DB Exception : "+e.getMessage());
        System.exit(1);
      } 
      jTextAreaDB.insert(sb.toString(),0);
      jTextAreaDB.setVisible(true);
    }//GEN-LAST:event_jButtonExecMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
      try{
          //DriverManager.getConnection("jdbc:derby:;shutdown=true");
          conn.close();
      }
      catch(SQLException e){} 
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAgenda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExec;
    private javax.swing.JComboBox jComboBoxTip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDB;
    private javax.swing.JTextField jTextFieldEntit;
    // End of variables declaration//GEN-END:variables
}
